#!/usr/bin/env python3
"""Stop the test suite writing over real reports.

THE INCIDENT THIS EXISTS TO PREVENT, 2026-09-07
------------------------------------------------
`common.mcp_sql --selftest` defaults `--report` to var/reports/mcp_sql_selftest.txt.
Four tests called `main(["--selftest"])` without overriding it, so running
pytest in D:\\Trading REPLACED the real selftest result -- the file that records
whether the read-only login is actually read-only -- with the output of a test
whose fake connection error is the string

    "mssql+pyodbc://trading-algo:hunter2@localhost/Trading failed"

That is not a crash. It is a plausible-looking failure report, with a real
username in it, sitting at the real path, timestamped minutes ago. It sent us
diagnosing a database connection that was never broken, and it destroyed the
measurement it overwrote.

Nearly every tool in this project defaults --out into var/reports/, by design
(PROGRAM_INDEX section 3: "reports write themselves"). So this is not one
careless test; it is a trap laid for every test that calls a main().

THE RULE
--------
A test may write anywhere except the repo's var/. Tests get tmp_path. If a
test writes a report, it passes an explicit path into tmp_path.

This fails loudly rather than redirecting quietly: a test with an unintended
side effect is a bug in the test, and silently sandboxing it would leave the
same tool free to surprise someone else.

WIDENED 2026-09-16, BECAUSE THE GUARD WAS NARROWER THAN ITS OWN LESSON
-----------------------------------------------------------------------
Until today this hooked exactly ONE function: `report_io.emit`. That is the
route a report takes, and reports were what the 2026-09-07 incident destroyed.
It is not the only route into var/.

The portal repo found the same class of defect in its own suite on 2026-09-15
and fixed it more thoroughly than this file had: three of its tests wrote and
then UNLINKED real credentials -- an auth.env and an agent token -- so every
`pytest` run destroyed the portal's login settings. One of those tests passed
only because another had just deleted the file first.

Nothing in this file would have caught that shape here either. `open(p, "w")`,
`Path.write_text`, `unlink`, `os.replace` -- all of them reach var/ without
going anywhere near `emit`. And what sits in var/ here is worse than a report:

    var/state/holdout.json    the LOCKED HOLDOUT, cut 2026-09-07, unspent
    var/fills/*.csv           the only look-ahead-free evidence in the project
    var/archive/watchlist_*   the record of what the live screen surfaced

The holdout is the one file that cannot be regenerated by re-running anything.
A test that truncated it would destroy the project's only out-of-sample
measurement, and nothing would raise.

So the guard now intercepts the file-mutating calls themselves, and fires
BEFORE the call rather than after -- a check that runs after the write has
already happened is a report, not a guard.
"""
from __future__ import annotations

from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
NAMES = ("var", "bar_cache", "bar_cache_db")


def _roots() -> tuple[Path, ...]:
    r"""Every spelling of a protected directory, resolved AND literal.

    D:\TradingProd\var is a junction to D:\Trading\var. The path being
    written resolves through it; a root that does not is then a different
    string, relative_to says no, and the guard waves through a write into the
    very directory it exists to protect. That is not hypothetical -- running
    this suite from the production checkout on 2026-09-14 replaced
    var/reports/mcp_sql_selftest.txt for the second time, the first being the
    incident this guard was written for.

    Both spellings are kept because either can be the one that matches: the
    resolved root catches a write through the junction, the literal root
    catches a path that was never resolved (a non-existent parent on some
    platforms, or a root that is itself unreadable).
    """
    roots: list[Path] = []
    for name in NAMES:
        here = REPO / name
        roots.append(here)
        try:
            roots.append(here.resolve())
        except OSError:                                     # pragma: no cover
            pass
    return tuple(dict.fromkeys(roots))


PROTECTED = _roots()


def _protected(p: Path) -> Path | None:
    """The protected root `p` sits inside, or None.

    Checks the path both as given and resolved, so neither a junction in the
    path nor one in the root can make a protected location look ordinary.
    """
    candidates = []
    try:
        candidates.append(Path(p).resolve())
    except OSError:
        pass
    candidates.append(Path(p) if Path(p).is_absolute() else Path.cwd() / p)

    for candidate in candidates:
        for root in PROTECTED:
            try:
                candidate.relative_to(root)
            except ValueError:
                continue
            return root
    return None


WRITE_MODES = set("wxa+")


def _refuse(op: str, target, root: Path):
    raise AssertionError(
        f"a test tried to {op} {target} inside {root}.\n"
        "That is a real artefact directory. var/state/holdout.json is the "
        "locked holdout and cannot be regenerated; var/fills/ is the only "
        "look-ahead-free evidence in the project.\n"
        "Use tmp_path. If a tool defaults its output into var/, pass it an "
        "explicit path under tmp_path instead.")


def _check(op: str, target):
    if target is None:
        return
    try:
        p = Path(target)
    except TypeError:                                       # a file descriptor
        return
    root = _protected(p)
    if root is not None:
        _refuse(op, target, root)


@pytest.fixture(autouse=True)
def no_writes_to_real_artefacts(monkeypatch):
    """Refuse any write, create, rename or delete inside the real artefact
    directories -- checked BEFORE the call, never after."""
    import builtins
    import os
    import shutil

    from common import report_io

    real_emit = report_io.emit

    def guarded_emit(text, out=None, *, header=""):
        _check("write", out)
        return real_emit(text, out, header=header)

    monkeypatch.setattr(report_io, "emit", guarded_emit)

    real_open = builtins.open

    def guarded_open(file, mode="r", *a, **k):
        if WRITE_MODES & set(str(mode)):
            _check(f"open({mode!r})", file)
        return real_open(file, mode, *a, **k)

    monkeypatch.setattr(builtins, "open", guarded_open)

    # Path methods, which do NOT go through builtins.open.
    for name, op in (("write_text", "write"), ("write_bytes", "write"),
                     ("unlink", "delete"), ("mkdir", "create"),
                     ("touch", "create"), ("rmdir", "delete")):
        real = getattr(Path, name)

        def make(real=real, op=op):
            def wrapper(self, *a, **k):
                _check(op, self)
                return real(self, *a, **k)
            return wrapper
        monkeypatch.setattr(Path, name, make())

    for name, op in (("rename", "rename"), ("replace", "replace")):
        real = getattr(Path, name)

        def make_two(real=real, op=op):
            def wrapper(self, target, *a, **k):
                _check(op, self)
                _check(f"{op} onto", target)
                return real(self, target, *a, **k)
            return wrapper
        monkeypatch.setattr(Path, name, make_two())

    # os-level equivalents. `os.replace` is how an atomic write lands, so a
    # tool that writes to a temp file and replaces the real one would reach
    # var/ without ever opening a protected path.
    for mod, name, op, two in ((os, "remove", "delete", False),
                               (os, "unlink", "delete", False),
                               (os, "rename", "rename", True),
                               (os, "replace", "replace", True),
                               (shutil, "rmtree", "delete", False),
                               (shutil, "copy", "copy onto", True),
                               (shutil, "copyfile", "copy onto", True),
                               (shutil, "move", "move onto", True)):
        real = getattr(mod, name)

        def make_os(real=real, op=op, two=two):
            def wrapper(a, *rest, **k):
                if two:
                    _check(f"{op}", rest[0] if rest else None)
                else:
                    _check(op, a)
                return real(a, *rest, **k)
            return wrapper
        monkeypatch.setattr(mod, name, make_os())

    yield

def pytest_configure(config):
    """Register the markers this suite uses.

    Unregistered marks are only a warning, which is how a typo'd @pytest.mark
    silently marks nothing. `slow` gates the dry-session replays: they step a
    synthetic session minute by minute through the real trader and cost
    seconds rather than milliseconds. Run `pytest -m "not slow"` to skip them.
    """
    config.addinivalue_line(
        "markers", "slow: steps a session through the real trader; seconds")
