#!/usr/bin/env python3
"""Does the artefact guard actually fire, on every route into var/?

The guard is an autouse fixture in tests/conftest.py. Until 2026-09-16 it
hooked exactly one function, `report_io.emit`, and the whole suite passed --
which is also what it would do if it hooked nothing at all. A guard that never
fires is indistinguishable from its own absence, and that is the failure this
project keeps finding.

So each route is exercised against a real protected path. Nothing here writes:
the guard has to raise BEFORE the call, so if any of these tests leaves a file
behind, the guard fired too late.

The target is var/state/holdout.json on purpose. It was cut 2026-09-07, it is
unspent, and it is the one file in the project that cannot be regenerated by
re-running anything.
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path

import pytest

# the guard lives in tests/conftest.py, which pytest loads as a plugin rather
# than as an importable module -- reach it through sys.modules so this file
# tests THE GUARD IN FORCE, not a second import of the same source.
#
# BY PATH IDENTITY, NOT BY MATCHING THE END OF A STRING. The first version of
# this compared `__file__.replace('\\\\', '/').endswith('tests/conftest.py')`,
# which is wrong twice over. `'\\\\'` in a non-raw literal is TWO backslashes
# and a Windows path has one, so the normalisation normalised nothing and the
# whole suite failed to collect on the only platform it was written for. And
# a suffix match would have accepted any other project's tests/conftest.py
# that happened to be imported -- this file would then have reported on a
# guard that is not the one protecting this run.
CONFTEST = Path(__file__).resolve().parent / "conftest.py"


def find_guard(modules) -> object:
    """The loaded conftest at CONFTEST, or None. Takes the mapping so it can
    be tested against a decoy rather than only against the real one."""
    for mod in list(modules.values()):
        f = getattr(mod, "__file__", None)
        if not f:
            continue
        try:
            if Path(f).resolve() == CONFTEST:
                return mod
        except (OSError, ValueError):        # a __file__ that is not a path
            continue                        # ValueError: embedded null byte
    return None


def _guard_module():
    import sys
    mod = find_guard(sys.modules)
    if mod is None:
        raise AssertionError(
            f"the guard is off -- no loaded module is {CONFTEST}")
    return mod


G = _guard_module()

HOLDOUT = G.REPO / "var" / "state" / "holdout.json"
FILLS = G.REPO / "var" / "fills" / "mcl_fills_20260915.csv"
CACHE = G.REPO / "bar_cache" / "anything.parquet"


def test_the_guard_is_located_by_path_and_not_by_the_end_of_a_string():
    """A DECOY: another checkout's tests/conftest.py, imported for any reason.

    A suffix match accepts it, and every assertion in this file then reports
    on a guard that is not the one protecting this run -- green, and about
    the wrong object. Path identity rejects it.
    """
    decoy = type(pytest)("decoy")
    decoy.__file__ = str(Path("/somewhere/else/tests/conftest.py"))
    assert find_guard({"decoy": decoy}) is None


def test_a_module_with_no_usable_file_is_skipped_rather_than_raising():
    """Namespace packages and frozen modules carry a `__file__` that is None
    or not a path. One of them must not take the whole collection down --
    which is a collection error, so it takes the SUITE down, not one test."""
    ns = type(pytest)("ns")
    ns.__file__ = None
    weird = type(pytest)("weird")
    weird.__file__ = "\x00not-a-path"
    assert find_guard({"ns": ns, "weird": weird}) is None


def test_the_conftest_it_found_is_this_directory_s_conftest():
    """Anchored to THIS file's folder, so a tests/ tree moved or vendored
    elsewhere cannot silently satisfy it."""
    assert Path(G.__file__).resolve() == CONFTEST
    assert CONFTEST.parent == Path(__file__).resolve().parent


def test_the_protected_roots_are_what_we_think_they_are():
    assert G._protected(HOLDOUT) is not None
    assert G._protected(FILLS) is not None
    assert G._protected(CACHE) is not None
    assert G._protected(G.REPO / "common" / "entry_place.py") is None


@pytest.mark.parametrize("mode", ["w", "a", "x", "wb", "r+", "w+b"])
def test_open_for_writing_is_refused(mode):
    with pytest.raises(AssertionError, match="holdout"):
        open(HOLDOUT, mode)    # mode is parametrised; the encoding guard skips it


def test_open_for_reading_is_allowed_and_still_works():
    """The guard must not make var/ unreadable. Tests legitimately READ real
    artefacts -- `paper_fill_is_rebuildable` loads the live fill logs."""
    p = G.REPO / "var" / "fills" / "mcl_fills_20260903.csv"
    if not p.exists():
        pytest.skip("no live fill log in this checkout")
    with open(p, "r", encoding="utf-8-sig") as fh:
        assert fh.readline().startswith("ts_et")


def test_path_write_text_and_write_bytes_are_refused():
    with pytest.raises(AssertionError):
        Path(HOLDOUT).write_text("{}", encoding="utf-8")
    with pytest.raises(AssertionError):
        Path(HOLDOUT).write_bytes(b"{}")


def test_unlink_is_refused():
    """The portal repo's defect, exactly: a test that wrote a credential and
    removed it in a finally. Deleting is not writing and went unguarded."""
    with pytest.raises(AssertionError, match="delete"):
        Path(HOLDOUT).unlink()
    with pytest.raises(AssertionError, match="delete"):
        os.remove(HOLDOUT)
    with pytest.raises(AssertionError, match="delete"):
        os.unlink(HOLDOUT)


def test_rmtree_is_refused():
    with pytest.raises(AssertionError, match="delete"):
        shutil.rmtree(G.REPO / "var" / "state")


def test_replace_onto_a_protected_path_is_refused(tmp_path):
    """An atomic write lands as os.replace(temp, real). The SOURCE is in
    tmp_path and perfectly legal; the destination is the holdout. A guard that
    only looked at the first argument would wave this through -- and this is
    the shape every careful writer in this repo uses."""
    src = tmp_path / "new.json"
    src.write_text("{}", encoding="utf-8")
    with pytest.raises(AssertionError, match="replace"):
        os.replace(src, HOLDOUT)
    with pytest.raises(AssertionError, match="replace"):
        Path(src).replace(HOLDOUT)


def test_rename_onto_a_protected_path_is_refused(tmp_path):
    src = tmp_path / "new.json"
    src.write_text("{}", encoding="utf-8")
    with pytest.raises(AssertionError, match="rename"):
        os.rename(src, HOLDOUT)


def test_copy_onto_a_protected_path_is_refused(tmp_path):
    src = tmp_path / "new.json"
    src.write_text("{}", encoding="utf-8")
    with pytest.raises(AssertionError, match="copy"):
        shutil.copy(src, HOLDOUT)
    with pytest.raises(AssertionError, match="copy"):
        shutil.copyfile(src, HOLDOUT)


def test_mkdir_inside_a_protected_root_is_refused():
    """THE ORDERING POINT, checked where it can actually be checked.

    The first version of this asserted "scratch_dir does not exist" from a
    separate test at the end of the file. That is a global assertion about the
    working tree, and it failed the moment a mutation run -- one that moved the
    check to AFTER the call, exactly the thing being tested -- left the
    directory behind. The assertion was right; its scope was wrong.

    The existence check belongs beside the call that would create it."""
    d = G.REPO / "var" / "reports" / "scratch_dir"
    existed = d.exists()
    with pytest.raises(AssertionError, match="create"):
        d.mkdir(parents=True)
    assert d.exists() == existed, \
        "the guard fired AFTER the call -- the directory was created first"


def test_tmp_path_is_completely_unaffected(tmp_path):
    """The guard must cost a well-behaved test nothing at all, or it will be
    worked around."""
    p = tmp_path / "a" / "b.txt"
    p.parent.mkdir(parents=True)
    p.write_text("fine", encoding="utf-8")
    assert p.read_text(encoding="utf-8") == "fine"
    q = tmp_path / "c.txt"
    p.replace(q)
    assert q.exists() and not p.exists()
    q.unlink()
    assert not q.exists()
    shutil.rmtree(tmp_path / "a")


def test_the_holdout_is_exactly_as_it_was(tmp_path):
    """Every route above was aimed at var/state/holdout.json. If any of them
    landed, the project's only out-of-sample measurement is gone and nothing
    else in the suite would notice."""
    h = G.REPO / "var" / "state" / "holdout.json"
    if not h.exists():
        pytest.skip("no holdout in this checkout")
    before = h.stat()
    assert before.st_size > 0
    assert h.stat().st_mtime == before.st_mtime
