#!/usr/bin/env python3
"""Cut the temporal holdout, once, before any strategy is scored on it.

    python -m common.holdout --cut \
        var/state/screen_pairs_consolidated.json var/state/screen_rejects.json
    python -m common.holdout --check          # is the committed cut still valid?

WHY NOW, AND WHY COMMITTED
--------------------------
Six strategies are about to be scored against one universe: ORB, three from the
2026-09-07 source videos, and the three that already exist. Test enough
strategies on one dataset and the best one looks good by chance -- that is not
a risk, it is arithmetic. The defence is a slice of time that nothing is fitted
on and nothing is peeked at, decided BEFORE the strategies run.

A holdout you can re-cut after seeing a result is not a holdout. So this cut is
written to a TRACKED file at the repo root, not to var/, and it records a
fingerprint of the universe it was cut from. Re-cutting is then a commit that
shows up in a diff, rather than a file quietly changing on one machine.

The previous holdout (`var/state/holdout_pairs_2026H2.json`) could not be
committed and was not: it is a list of which symbols Ben traded on which
mornings, which is real trading history. **This one is different in kind.** It
is a split of the rule-generated screened universe -- public market data run
through `common/screen.py` -- so it contains nothing private, travels with the
repo, and cannot silently differ between machines.

WHAT THE TWO SPLITS ARE FOR, BECAUSE THEY ARE NOT THE SAME TEST
---------------------------------------------------------------
1. **The locked holdout** -- the last 30% of sessions. Nothing is fitted on it,
   nothing is measured on it, until a strategy's go/no-go is being decided.
   This is the multiple-comparisons defence.

2. **The both-halves split** -- the training portion cut in half by date. This
   is the project's existing standard of evidence: require the effect in BOTH
   halves, split point not swept. It runs during development and is not the
   holdout.

Using the locked set as a development check destroys it. That is the only way
to get this wrong and it is easy to do by accident -- but nothing here can
detect it, and this module does not pretend to. An earlier draft of this
docstring promised a counter of reads against the locked set; nothing
incremented it, so the field was removed rather than shipped as decoration. The
control is the commit history and the person running the command.

WHAT THIS CANNOT FIX
--------------------
MC5 has already been scored over the whole period, including these sessions
(`screened_universe_results.md`). A holdout cut today is clean for ORB and for
anything built from the video set, and it is NOT clean for MC5. Recorded here
rather than glossed, because the temptation later will be to quote MC5's
holdout figure as though it were out-of-sample. It is not.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# Tracked, at the repo root, on purpose. See the docstring.
CUT_PATH = Path(__file__).resolve().parents[1] / "holdout.json"

# The fraction of SESSIONS held back. Chosen before looking at any result and
# recorded here so the choice is visible: 30% of 545 sessions is 164, which is
# enough for a drop-top-5 check to still mean something (removing 5 symbols
# from a 164-session sample is not removing the sample).
LOCK_FRACTION = 0.30


def sessions(paths) -> list[str]:
    """Every distinct session date across the given pair lists, sorted."""
    days: set[str] = set()
    for p in paths:
        for row in json.loads(Path(p).read_text()):
            days.add(row["date"])
    return sorted(days)


def fingerprint(paths) -> str:
    """A hash of the UNIVERSE, not of the files.

    Deliberately not a file hash: the pair lists are regenerated by re-running
    the screen, and a re-run that produces identical pairs should not invalidate
    the cut. What must not change silently is the set of symbol-days.
    """
    pairs = set()
    for p in paths:
        for row in json.loads(Path(p).read_text()):
            pairs.add((row["symbol"], row["date"]))
    h = hashlib.sha256()
    for s, d in sorted(pairs):
        h.update(f"{s}|{d}\n".encode())
    return h.hexdigest()


def split(days: list[str], lock_fraction: float = LOCK_FRACTION) -> dict:
    """Two boundaries, both derived by rule rather than chosen.

    The split points are a fraction of the SESSION COUNT, not a calendar date,
    so the halves carry comparable numbers of trading days rather than
    comparable amounts of wall-clock time.
    """
    if len(days) < 20:
        raise ValueError(f"only {len(days)} sessions -- too few to split")
    lock_i = int(len(days) * (1.0 - lock_fraction))
    lock_from = days[lock_i]
    train = [d for d in days if d < lock_from]
    # The both-halves boundary is the median of the TRAINING portion, so that
    # locking the holdout does not move it.
    mid = train[len(train) // 2]
    return {
        "lock_from": lock_from,
        "train_first": train[0], "train_last": train[-1],
        "both_halves_split": mid,
        "n_sessions": len(days),
        "n_train": len(train),
        "n_locked": len(days) - len(train),
        "n_early": sum(1 for d in train if d < mid),
        "n_late": sum(1 for d in train if d >= mid),
    }


def cut(paths, lock_fraction: float = LOCK_FRACTION) -> dict:
    days = sessions(paths)
    rec = split(days, lock_fraction)
    rec.update({
        "cut_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "lock_fraction": lock_fraction,
        # BASENAMES, not full paths. This file is committed and read on other
        # machines; recording the absolute path it happened to be cut from
        # says nothing true about where the universe lives. The fingerprint is
        # what identifies it.
        "sources": sorted(Path(p).name for p in paths),
        "universe_fingerprint": fingerprint(paths),
        "note": ("The locked sessions are OUT OF SAMPLE for anything built "
                 "after cut_at. They are NOT out of sample for MC5, MCL or "
                 "VW9, which were scored over the whole period on 2026-09-07."),
    })
    return rec


def load() -> dict | None:
    if not CUT_PATH.exists():
        return None
    return json.loads(CUT_PATH.read_text())


def is_locked(rec: dict, day: str) -> bool:
    return str(day) >= rec["lock_from"]


def partition(rec: dict, pairs) -> dict:
    """Split symbol-day pairs into the three sets, by date."""
    out = {"early": [], "late": [], "locked": []}
    for p in pairs:
        d = p["date"] if isinstance(p, dict) else p[1]
        if is_locked(rec, d):
            out["locked"].append(p)
        elif str(d) < rec["both_halves_split"]:
            out["early"].append(p)
        else:
            out["late"].append(p)
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Cut or verify the holdout")
    ap.add_argument("--cut", nargs="+", metavar="PAIRS.json",
                    help="cut a new holdout from these pair lists")
    ap.add_argument("--check", nargs="*", metavar="PAIRS.json",
                    help="verify the committed cut, optionally against the "
                         "current pair lists")
    ap.add_argument("--lock-fraction", type=float, default=LOCK_FRACTION)
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing cut (this is a real decision)")
    a = ap.parse_args(argv)

    if a.cut:
        existing = load()
        if existing and not a.force:
            print(f"A cut already exists at {CUT_PATH}:")
            print(f"  cut at        {existing['cut_at']}")
            print(f"  locked from   {existing['lock_from']}  "
                  f"({existing['n_locked']} sessions)")
            print("\nRE-CUTTING AFTER RESULTS HAVE BEEN SEEN DESTROYS THE")
            print("HOLDOUT. If the universe genuinely changed, pass --force")
            print("and say so in the commit message, so the change is visible")
            print("in the diff rather than only on one machine.")
            return 1
        rec = cut([Path(p) for p in a.cut], a.lock_fraction)
        CUT_PATH.write_text(json.dumps(rec, indent=2) + "\n")
        print(f"wrote {CUT_PATH}\n")
        print(f"  sessions          {rec['n_sessions']:,}  "
              f"({rec['train_first']} -> {rec['lock_from']} -> last)")
        print(f"  training          {rec['n_train']:,}  "
              f"(early {rec['n_early']:,} / late {rec['n_late']:,}, "
              f"split {rec['both_halves_split']})")
        print(f"  LOCKED            {rec['n_locked']:,}  "
              f"from {rec['lock_from']}")
        print(f"  fingerprint       {rec['universe_fingerprint'][:16]}...")
        print("\n  COMMIT THIS FILE. A holdout that lives on one machine is")
        print("  a holdout that can be re-cut without anyone seeing.")
        return 0

    rec = load()
    if rec is None:
        print(f"no cut at {CUT_PATH} -- run --cut first")
        return 1
    print(f"cut at        {rec['cut_at']}")
    print(f"locked from   {rec['lock_from']}  ({rec['n_locked']} sessions)")
    print(f"both halves   {rec['both_halves_split']}  "
          f"({rec['n_early']} / {rec['n_late']})")

    if a.check:
        now = fingerprint([Path(p) for p in a.check])
        same = now == rec["universe_fingerprint"]
        print(f"\nuniverse fingerprint: {'MATCHES' if same else 'DIFFERS'}")
        if not same:
            print("  The screened universe is not the one this was cut from.")
            print("  The date boundaries still apply, but the locked set now")
            print("  contains symbol-days that did not exist at cut time.")
            print("  Decide deliberately; do not just re-cut.")
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
