#!/usr/bin/env python3
"""W16 session-baselines neighbour grid: REGISTERED_w16_session_baselines.md
sec 7.3 ("Neighbour grid -- 9 cells per baseline per market, net at L2,
training side") and sec 9 criterion 8 ("At least 6 of the 9 neighbour
cells net > $0 at L2"). Board W16-0005.

Each baseline gets its own 3x3 grid of re-parameterized rule variants:

    B1  range length {15, 30, 60 min} x target {1.5, 2, 3} x risk
    B2  entry {15:45, 16:00, 16:15}   x exit   {09:15, 09:30, 09:45}
    B3  bar size {1, 2, 5 min}        x flip-confirm {1, 2, 3} closes

Registered values are the MIDDLE entry of each tuple below, per sec 7.3's
own table -- not assumed to be the first or the "default" one, so this
module never treats one cell as more important than another (sec 7.3:
"The grid is a robustness check, not a search: no cell can replace the
registered rule"). Every cell is generated by the SAME strategy.w16.signals
functions the registered run uses (made to accept these dimensions as
parameters -- strategy.w16.signals' own docstring: "One detection engine,
two consumers -- not two copies that could silently drift apart"), and
priced with the SAME strategy.w16.runner.price_all/summarize the registered
run uses. Nothing here computes a control, a bootstrap, or a pass/fail --
the caller (strategy.w16.runner.run_cell) supplies the resulting
`share_positive` to `score_cell`'s own criterion 8, and REGISTERED sec 12
is explicit that grid cells are never picked as a replacement rule because
one did better.

B2's grid needs bars slightly outside the registered RTH window (the
registered rule itself only ever reads the 15:59 close and the 09:30
open). `strategy.w16.sessions.session_frames_wide` re-slices the SAME
1-minute archive B1/B3 already use RTH-windowed, with a wider clock-time
margin, so those extra bars exist to look up. A day where the exact bar at
a requested clock time is missing (an early close asked for a 16:15
entry, most often) is skipped by `strategy.w16.signals.overnight_trade`
itself -- not specially handled here, and not a bias worth correcting on
a robustness check run over ~3,400 training sessions.
"""
from __future__ import annotations

import itertools
from datetime import time as dtime

import pandas as pd

from strategy.w16 import holdout as H
from strategy.w16 import sessions as S

B1_RANGE_MINUTES = (15, 30, 60)
B1_TARGET_R = (1.5, 2.0, 3.0)
B2_ENTRY_TIMES = (dtime(15, 45), dtime(16, 0), dtime(16, 15))
B2_EXIT_TIMES = (dtime(9, 15), dtime(9, 30), dtime(9, 45))
B3_BAR_MINUTES = (1, 2, 5)
B3_FLIP_CONFIRM = (1, 2, 3)

REGISTERED_CELL = {
    "B1": (30, 2.0),
    "B2": (dtime(16, 0), dtime(9, 30)),
    "B3": (1, 1),
}

DIMENSIONS = {
    "B1": (B1_RANGE_MINUTES, B1_TARGET_R),
    "B2": (B2_ENTRY_TIMES, B2_EXIT_TIMES),
    "B3": (B3_BAR_MINUTES, B3_FLIP_CONFIRM),
}

BASELINES = ("B1", "B2", "B3")
LEVEL = "L2"                # sec 5 item 6 / sec 7.3: "net at L2"


def cells(baseline: str) -> list[tuple]:
    """The 9 (dim1, dim2) combinations for one baseline, in a fixed
    (product) order -- sec 7.3's full 3x3 table, not just the registered
    cell's own row/column."""
    d1, d2 = DIMENSIONS[baseline]
    return list(itertools.product(d1, d2))


def run_neighbour_grid(baseline: str, market: str, archive=None, *,
                       df_1m: pd.DataFrame | None = None,
                       frames: dict[str, pd.DataFrame] | None = None) -> dict:
    """Runs all 9 sec 7.3 cells for one (baseline, market), training side
    only, priced at L2. `df_1m`/`frames` let a caller that already loaded
    the archive (strategy.w16.runner.run_cell) pass them straight in
    rather than paying for a second load of the full ES/NQ archive.

    Returns {"baseline", "market", "cells": [{"dim1", "dim2", "n_trades",
    "net"} x 9], "n_positive", "n_total": 9, "share_positive"}. Never picks
    a best cell (sec 7.3: "the grid never replaces the registered rule")."""
    if baseline not in BASELINES:
        raise ValueError(f"unknown baseline {baseline!r}; expected one of {BASELINES}")

    from strategy.w16 import runner as R                    # deferred: R imports this module
    from strategy.w16.preflight import load_root_bars, session_frames

    if df_1m is None:
        df_1m = load_root_bars(archive, market)
    if frames is None:
        frames = session_frames(df_1m)
    all_dates = sorted(frames.keys())
    train_dates, _, _ = H.split_dates(all_dates)
    train_dates = list(train_dates)
    train_set = set(train_dates)

    rows: list[dict] = []

    if baseline == "B1":
        for range_minutes, target_r in cells("B1"):
            trades = R.generate_b1_trades(frames, market, train_dates,
                                          target_r=target_r, range_minutes=range_minutes)
            summary = R.summarize(R.price_all(trades, LEVEL))
            rows.append({"dim1": range_minutes, "dim2": target_r,
                        "n_trades": summary["n_trades"], "net": summary["net"]})

    elif baseline == "B2":
        frames_wide = S.session_frames_wide(df_1m)
        ordered = [d for d in sorted(frames_wide) if d in train_set]
        for entry_time, exit_time in cells("B2"):
            trades = R.generate_b2_trades(frames_wide, market, ordered,
                                          entry_time=entry_time, exit_time=exit_time)
            summary = R.summarize(R.price_all(trades, LEVEL))
            rows.append({"dim1": entry_time, "dim2": exit_time,
                        "n_trades": summary["n_trades"], "net": summary["net"]})

    elif baseline == "B3":
        # bar_minutes is the outer loop and cached across the 3 flip_confirm
        # values -- resampling is the expensive part of a B3 cell, and the
        # 9 cells only need 3 distinct resamplings, not 9.
        for bar_minutes in B3_BAR_MINUTES:
            resampled = {d: S.resample_session_bars(frames[d], bar_minutes)
                        for d in train_dates if d in frames}
            for flip_confirm in B3_FLIP_CONFIRM:
                trades = R.generate_b3_trades(resampled, market, train_dates,
                                              flip_confirm=flip_confirm)
                summary = R.summarize(R.price_all(trades, LEVEL))
                rows.append({"dim1": bar_minutes, "dim2": flip_confirm,
                            "n_trades": summary["n_trades"], "net": summary["net"]})

    n_positive = sum(1 for r in rows if r["net"] > 0)
    return {"baseline": baseline, "market": market, "cells": rows,
           "n_positive": n_positive, "n_total": len(rows),
           "share_positive": n_positive / len(rows) if rows else 0.0}
